FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scraper/ ./scraper/
COPY scrapy.cfg .

ENTRYPOINT ["scrapy", "crawl"]
CMD ["webscraper_cars"]